// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");

var SetMessage = Caml_exceptions.create("Action-ReactTemplate.SetMessage");

var SetLookupURL = Caml_exceptions.create("Action-ReactTemplate.SetLookupURL");

var AliasListLoading = Caml_exceptions.create("Action-ReactTemplate.AliasListLoading");

var AliasListLoadingFailed = Caml_exceptions.create("Action-ReactTemplate.AliasListLoadingFailed");

var AliasListLoaded = Caml_exceptions.create("Action-ReactTemplate.AliasListLoaded");

var AliasListIsStale = Caml_exceptions.create("Action-ReactTemplate.AliasListIsStale");

var GeneratingAlias = Caml_exceptions.create("Action-ReactTemplate.GeneratingAlias");

var GeneratedAlias = Caml_exceptions.create("Action-ReactTemplate.GeneratedAlias");

var GeneratingAliasFailed = Caml_exceptions.create("Action-ReactTemplate.GeneratingAliasFailed");

var ReplaceState = Caml_exceptions.create("Action-ReactTemplate.ReplaceState");

exports.SetMessage             = SetMessage;
exports.SetLookupURL           = SetLookupURL;
exports.AliasListLoading       = AliasListLoading;
exports.AliasListLoadingFailed = AliasListLoadingFailed;
exports.AliasListLoaded        = AliasListLoaded;
exports.AliasListIsStale       = AliasListIsStale;
exports.GeneratingAlias        = GeneratingAlias;
exports.GeneratedAlias         = GeneratedAlias;
exports.GeneratingAliasFailed  = GeneratingAliasFailed;
exports.ReplaceState           = ReplaceState;
/* No side effect */
