// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");

var Thunk = Caml_exceptions.create("ReduxThunk-ReactTemplate.Thunk");

exports.Thunk = Thunk;
/* No side effect */
