// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Js_dict = require("bs-platform/lib/js/js_dict.js");

var initial_000 = /* aliasStatuses */{ };

var initial = /* record */[
  initial_000,
  /* dataIsStale : false */0,
  /* messages : [] */0
];

function cloneDict(d) {
  return Js_dict.fromArray(Js_dict.entries(d));
}

function setAliasStatus(state, id, status) {
  var aliasStatuses = Js_dict.fromArray(Js_dict.entries(state[/* aliasStatuses */0]));
  aliasStatuses[id] = status;
  return aliasStatuses;
}

exports.initial        = initial;
exports.cloneDict      = cloneDict;
exports.setAliasStatus = setAliasStatus;
/* Js_dict Not a pure module */
