// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var List              = require("bs-platform/lib/js/list.js");
var $$String          = require("bs-platform/lib/js/string.js");
var Js_dict           = require("bs-platform/lib/js/js_dict.js");
var Url$ReactTemplate = require("../url.bs.js");

var urlInQuery = List.find_all((function (p) {
          return +($$String.lowercase(p[/* key */0]) === "url");
        }))(List.rev(Url$ReactTemplate.Params[/* toList */1](Url$ReactTemplate.Params[/* ofString */2](window.location.search))));

var lookupInitialValue;

if (urlInQuery) {
  var match = urlInQuery[0][/* value */1];
  lookupInitialValue = match ? match[0] : "";
} else {
  lookupInitialValue = "";
}

var initial_000 = /* aliasStatuses */{ };

var initial = /* record */[
  initial_000,
  /* listIsStale : false */0,
  /* lookupInitialValue */lookupInitialValue,
  /* lookupURL : Unset */974938825,
  /* messages : [] */0
];

function cloneDict(d) {
  return Js_dict.fromArray(Js_dict.entries(d));
}

function setAliasStatus(state, id, status) {
  var aliasStatuses = Js_dict.fromArray(Js_dict.entries(state[/* aliasStatuses */0]));
  aliasStatuses[id] = status;
  return aliasStatuses;
}

exports.lookupInitialValue = lookupInitialValue;
exports.initial            = initial;
exports.cloneDict          = cloneDict;
exports.setAliasStatus     = setAliasStatus;
/* urlInQuery Not a pure module */
