// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Curry                    = require("bs-platform/lib/js/curry.js");
var Reductive                = require("reductive/src/reductive.js");
var ReduxThunk$ReactTemplate = require("./ReduxThunk.bs.js");

function logger(store, next, action) {
  console.log(action);
  var returnValue = Curry._1(next, action);
  console.log(Reductive.Store[/* getState */5](store));
  return returnValue;
}

function thunk(store, next, action) {
  if (action[0] === ReduxThunk$ReactTemplate.Thunk) {
    return Curry._1(action[1], store);
  } else {
    return Curry._1(next, action);
  }
}

exports.logger = logger;
exports.thunk  = thunk;
/* Reductive Not a pure module */
