// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Caml_obj                      = require("bs-platform/lib/js/caml_obj.js");
var Reductive                     = require("reductive/src/reductive.js");
var State$ReactTemplate           = require("./State.bs.js");
var Action$ReactTemplate          = require("./Action.bs.js");
var StoreMiddleware$ReactTemplate = require("./StoreMiddleware.bs.js");

function reducer(state, action) {
  if (action[0] === Action$ReactTemplate.SetMessage) {
    return /* record */[
            /* aliasStatuses */state[/* aliasStatuses */0],
            /* aliasList */state[/* aliasList */1],
            /* lookupInitialValue */state[/* lookupInitialValue */2],
            /* lookupURL */state[/* lookupURL */3],
            /* messages */State$ReactTemplate.addMessage(state, action[1], action[2])
          ];
  } else if (action[0] === Action$ReactTemplate.SetLookupURL) {
    var lookupURL = action[1];
    var match = Caml_obj.caml_equal(lookupURL, state[/* lookupURL */3]);
    var aliasList = match !== 0 ? state[/* aliasList */1] : /* Unloaded */879244094;
    return /* record */[
            /* aliasStatuses */state[/* aliasStatuses */0],
            /* aliasList */aliasList,
            /* lookupInitialValue */state[/* lookupInitialValue */2],
            /* lookupURL */lookupURL,
            /* messages */state[/* messages */4]
          ];
  } else if (action === Action$ReactTemplate.AliasListLoading) {
    var match$1 = state[/* aliasList */1];
    var aliasList$1 = typeof match$1 === "number" || match$1[0] !== 218348581 ? /* Loading */-700189092 : /* `Loaded */[
        218348581,
        /* tuple */[
          match$1[1][0],
          /* Reloading */724399881
        ]
      ];
    return /* record */[
            /* aliasStatuses */state[/* aliasStatuses */0],
            /* aliasList */aliasList$1,
            /* lookupInitialValue */state[/* lookupInitialValue */2],
            /* lookupURL */state[/* lookupURL */3],
            /* messages */state[/* messages */4]
          ];
  } else if (action[0] === Action$ReactTemplate.AliasListLoadingFailed) {
    return /* record */[
            /* aliasStatuses */state[/* aliasStatuses */0],
            /* aliasList : `Failed */[
              479410653,
              action[1]
            ],
            /* lookupInitialValue */state[/* lookupInitialValue */2],
            /* lookupURL */state[/* lookupURL */3],
            /* messages */state[/* messages */4]
          ];
  } else if (action[0] === Action$ReactTemplate.AliasListLoaded) {
    return /* record */[
            /* aliasStatuses */state[/* aliasStatuses */0],
            /* aliasList : `Loaded */[
              218348581,
              /* tuple */[
                action[1],
                /* Fresh */431224398
              ]
            ],
            /* lookupInitialValue */state[/* lookupInitialValue */2],
            /* lookupURL */state[/* lookupURL */3],
            /* messages */state[/* messages */4]
          ];
  } else if (action === Action$ReactTemplate.AliasListIsStale) {
    var aliasList$2 = State$ReactTemplate.markAliasListStale(state);
    return /* record */[
            /* aliasStatuses */state[/* aliasStatuses */0],
            /* aliasList */aliasList$2,
            /* lookupInitialValue */state[/* lookupInitialValue */2],
            /* lookupURL */state[/* lookupURL */3],
            /* messages */state[/* messages */4]
          ];
  } else if (action[0] === Action$ReactTemplate.GeneratingAlias) {
    var aliasStatuses = State$ReactTemplate.setAliasStatus(state, action[1], /* Saving */-674467366);
    return /* record */[
            /* aliasStatuses */aliasStatuses,
            /* aliasList */state[/* aliasList */1],
            /* lookupInitialValue */state[/* lookupInitialValue */2],
            /* lookupURL */state[/* lookupURL */3],
            /* messages */state[/* messages */4]
          ];
  } else if (action[0] === Action$ReactTemplate.GeneratedAlias) {
    var aliasStatuses$1 = State$ReactTemplate.setAliasStatus(state, action[1], /* Saved */179944039);
    var aliasList$3 = State$ReactTemplate.markAliasListStale(state);
    var messages = State$ReactTemplate.addMessage(state, /* Info */815031438, "Generated alias " + (action[2] + "."));
    return /* record */[
            /* aliasStatuses */aliasStatuses$1,
            /* aliasList */aliasList$3,
            /* lookupInitialValue */state[/* lookupInitialValue */2],
            /* lookupURL */state[/* lookupURL */3],
            /* messages */messages
          ];
  } else if (action[0] === Action$ReactTemplate.GeneratingAliasFailed) {
    var message = action[2];
    var aliasStatuses$2 = State$ReactTemplate.setAliasStatus(state, action[1], /* `Failed */[
          479410653,
          message
        ]);
    var messages$1 = State$ReactTemplate.addMessage(state, /* Error */106380200, message);
    return /* record */[
            /* aliasStatuses */aliasStatuses$2,
            /* aliasList */state[/* aliasList */1],
            /* lookupInitialValue */state[/* lookupInitialValue */2],
            /* lookupURL */state[/* lookupURL */3],
            /* messages */messages$1
          ];
  } else {
    return state;
  }
}

function reducerWrap(state, action) {
  var messages = State$ReactTemplate.clearExpiredMessages(state);
  var state$prime_000 = /* aliasStatuses */state[/* aliasStatuses */0];
  var state$prime_001 = /* aliasList */state[/* aliasList */1];
  var state$prime_002 = /* lookupInitialValue */state[/* lookupInitialValue */2];
  var state$prime_003 = /* lookupURL */state[/* lookupURL */3];
  var state$prime = /* record */[
    state$prime_000,
    state$prime_001,
    state$prime_002,
    state$prime_003,
    /* messages */messages
  ];
  return reducer(state$prime, action);
}

function thunkedLogger(store, next) {
  return (function (param) {
      return StoreMiddleware$ReactTemplate.thunk(store, (function (param) {
                    return StoreMiddleware$ReactTemplate.logger(store, next, param);
                  }), param);
    });
}

var store = Reductive.Store[/* create */0](reducerWrap, State$ReactTemplate.initial, /* Some */[thunkedLogger], /* () */0);

var partial_arg = Reductive.Store[/* dispatch */4];

function dispatch(param) {
  return partial_arg(store, param);
}

exports.reducer       = reducer;
exports.reducerWrap   = reducerWrap;
exports.thunkedLogger = thunkedLogger;
exports.store         = store;
exports.dispatch      = dispatch;
/* store Not a pure module */
