// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Opt$ReactTemplate = require("./Opt.bs.js");

function isNull(prim) {
  return +(prim == null);
}

function notNull(x) {
  return 1 - +(x == null);
}

function value(x) {
  return Opt$ReactTemplate.value((x == null) ? /* None */0 : [x]);
}

exports.isNull  = isNull;
exports.notNull = notNull;
exports.value   = value;
/* No side effect */
