// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var React               = require("react");
var Pervasives          = require("bs-platform/lib/js/pervasives.js");
var ReasonReact         = require("reason-react/src/ReasonReact.js");
var Alias$ReactTemplate = require("./alias.bs.js");

function str(prim) {
  return prim;
}

var component = ReasonReact.reducerComponent("AliasWidget");

function make(alias, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (param) {
      var id = Pervasives.string_of_int(Alias$ReactTemplate.id(alias));
      var className = param[/* state */2][/* saving */0] !== 0 ? "status-saving" : "status-saved";
      return React.createElement("article", {
                  className: className,
                  id: "alias-" + id
                }, React.createElement("h1", undefined, Alias$ReactTemplate.name(alias)), React.createElement("div", {
                      className: "status"
                    }, Alias$ReactTemplate.statusAsString(alias)));
    });
  newrecord[/* initialState */10] = (function () {
      return /* record */[/* saving : false */0];
    });
  newrecord[/* reducer */12] = (function (_, _$1) {
      return /* NoUpdate */0;
    });
  return newrecord;
}

exports.str       = str;
exports.component = component;
exports.make      = make;
/* component Not a pure module */
