// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


var graphqlURI = window.config.graphqlURI;

var aliasPrefix = window.config.aliasPrefix;

exports.graphqlURI  = graphqlURI;
exports.aliasPrefix = aliasPrefix;
/* graphqlURI Not a pure module */
