// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


var graphqlURI = window.config.graphqlURI;

var graphqlAuthHeader = window.config.graphqlAuthHeader;

var aliasPrefix = window.config.aliasPrefix;

var graphqlAuthHeader$1 = (graphqlAuthHeader == null) ? /* None */0 : [graphqlAuthHeader];

exports.graphqlURI        = graphqlURI;
exports.graphqlAuthHeader = graphqlAuthHeader$1;
exports.aliasPrefix       = aliasPrefix;
/* graphqlURI Not a pure module */
