// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact          = require("reason-react/src/ReasonReact.js");
var ReactCopyToClipboard = require("react-copy-to-clipboard");

function make(text, children) {
  return ReasonReact.wrapJsForReason(ReactCopyToClipboard.CopyToClipboard, {
              text: text
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
