// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var React                               = require("react");
var Js_boolean                          = require("bs-platform/lib/js/js_boolean.js");
var Pervasives                          = require("bs-platform/lib/js/pervasives.js");
var ReasonReact                         = require("reason-react/src/ReasonReact.js");
var MutationGenerateAlias$ReactTemplate = require("./MutationGenerateAlias.bs.js");

function str(prim) {
  return prim;
}

var component = ReasonReact.reducerComponent("GenerateAliasButton");

function make(url, appState, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (param) {
      var id = param[/* state */2][/* id */0];
      var match = appState[/* aliasStatuses */0][id];
      var match$1 = match !== undefined ? (
          typeof match === "number" ? (
              match >= 179944039 ? /* tuple */[
                  /* false */0,
                  "Generate Alias"
                ] : /* tuple */[
                  /* true */1,
                  "Generating..."
                ]
            ) : /* tuple */[
              /* false */0,
              "Failed generating. Try again?"
            ]
        ) : /* tuple */[
          /* false */0,
          "Generate Alias"
        ];
      return React.createElement("button", {
                  className: "add-alias",
                  disabled: Js_boolean.to_js_boolean(match$1[0]),
                  onClick: (function () {
                      return MutationGenerateAlias$ReactTemplate.run(id, url);
                    })
                }, match$1[1]);
    });
  newrecord[/* initialState */10] = (function () {
      return /* record */[/* id */Pervasives.string_of_float(Date.now())];
    });
  newrecord[/* reducer */12] = (function (_, _$1) {
      return /* NoUpdate */0;
    });
  return newrecord;
}

exports.str       = str;
exports.component = component;
exports.make      = make;
/* component Not a pure module */
