// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Curry                    = require("bs-platform/lib/js/curry.js");
var Reductive                = require("reductive/src/reductive.js");
var ReactDOMRe               = require("reason-react/src/ReactDOMRe.js");
var ReasonReact              = require("reason-react/src/ReasonReact.js");
var Store$ReactTemplate      = require("./store/Store.bs.js");
var LookupPage$ReactTemplate = require("./components/LookupPage.bs.js");

var make = Reductive.Provider[/* createMake */0](/* None */0, Store$ReactTemplate.store);

var StoreProvider = /* module */[/* make */make];

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, Curry._2(make, LookupPage$ReactTemplate.make, /* array */[])), "index");

exports.StoreProvider = StoreProvider;
/* make Not a pure module */
