// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var List                       = require("bs-platform/lib/js/list.js");
var $$Array                    = require("bs-platform/lib/js/array.js");
var React                      = require("react");
var Pervasives                 = require("bs-platform/lib/js/pervasives.js");
var ReasonReact                = require("reason-react/src/ReasonReact.js");
var Alias$ReactTemplate        = require("./alias.bs.js");
var AliasWidget$ReactTemplate  = require("./AliasWidget.bs.js");
var QueryAliases$ReactTemplate = require("./QueryAliases.bs.js");

function str(prim) {
  return prim;
}

var component = ReasonReact.statelessComponent("QueryAliases");

function make(url, appState, _) {
  var newrecord = component.slice();
  newrecord[/* willReceiveProps */3] = (function () {
      var match = appState[/* aliasList */1];
      if (typeof match !== "number") {
        if (match[0] !== 218348581 || match[1][1] !== 389603065) {
          
        } else {
          QueryAliases$ReactTemplate.reload(url);
        }
      }
      return /* () */0;
    });
  newrecord[/* didMount */4] = (function () {
      QueryAliases$ReactTemplate.run(url);
      return /* NoUpdate */0;
    });
  newrecord[/* render */9] = (function () {
      var match = appState[/* aliasList */1];
      var body;
      if (typeof match === "number") {
        body = React.createElement("p", {
              className: "status loading"
            }, "Loading...");
      } else if (match[0] >= 479410653) {
        body = React.createElement("p", {
              className: "status failure"
            }, match[1]);
      } else {
        var match$1 = match[1];
        var lst = match$1[0];
        if (lst) {
          var match$2 = List.partition((function (a) {
                  return +(Alias$ReactTemplate.status(a) === /* Enabled */-880661407);
                }), lst);
          var elementOfAlias = function (a) {
            return ReasonReact.element(/* Some */[Pervasives.string_of_int(Alias$ReactTemplate.id(a))], /* None */0, AliasWidget$ReactTemplate.make(a, (function () {
                              return QueryAliases$ReactTemplate.reload(url);
                            }), /* array */[]));
          };
          body = React.createElement("div", undefined, match$1[1] >= 724399881 ? React.createElement("p", {
                      className: "status reloading"
                    }, "Reloading...") : null, React.createElement("div", {
                    className: "enabled"
                  }, React.createElement("h2", undefined, "Enabled"), $$Array.map(elementOfAlias, $$Array.of_list(match$2[0]))), React.createElement("div", {
                    className: "disabled"
                  }, React.createElement("h2", undefined, "Disabled"), $$Array.map(elementOfAlias, $$Array.of_list(match$2[1]))));
        } else {
          body = React.createElement("p", {
                className: "status empty"
              }, "No aliases.");
        }
      }
      return React.createElement("section", {
                  className: "list"
                }, body);
    });
  return newrecord;
}

exports.str       = str;
exports.component = component;
exports.make      = make;
/* component Not a pure module */
