// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var React                     = require("react");
var ReasonReact               = require("reason-react/src/ReasonReact.js");
var LookupInput$ReactTemplate = require("./LookupInput.bs.js");

function str(prim) {
  return prim;
}

var component = ReasonReact.reducerComponent("LookupPage");

function make() {
  var onSubmit = function (text) {
    console.log("Bingi:", text);
    return /* () */0;
  };
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("section", undefined, React.createElement("h1", undefined, "OCamURL"), React.createElement("p", undefined, "Enter a URL or alias below."), ReasonReact.element(/* None */0, /* None */0, LookupInput$ReactTemplate.make("Hi there", onSubmit, /* array */[])));
    });
  newrecord[/* initialState */10] = (function () {
      return /* record */[/* input */""];
    });
  newrecord[/* reducer */12] = (function (_, _$1) {
      return /* NoUpdate */0;
    });
  return newrecord;
}

exports.str       = str;
exports.component = component;
exports.make      = make;
/* component Not a pure module */
