// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Curry                = require("bs-platform/lib/js/curry.js");
var Pervasives           = require("bs-platform/lib/js/pervasives.js");
var GraphqlTag           = require("graphql-tag");
var Apollo$ReactTemplate = require("./apollo.bs.js");

var query = GraphqlTag("\n  mutation RenameAlias($input: RenameAliasInput!) {\n    renameAlias(input: $input) {\n      error { code, message }\n      payload { actionTaken }\n    }\n  }\n");

var Config = /* module */[];

var Mutation = Apollo$ReactTemplate.Query(Config);

function run(name, newName) {
  var now = Pervasives.string_of_float(Date.now());
  var input = {
    clientMutationId: name + ("///" + (newName + ("///" + now))),
    name: name,
    newName: newName,
    disableAndAddIfUsed: true
  };
  var variables = /* Some */[{
      input: input
    }];
  return Curry._3(Mutation[/* send */3], /* Mutation */1035765577, query, variables);
}

exports.query    = query;
exports.Config   = Config;
exports.Mutation = Mutation;
exports.run      = run;
/* query Not a pure module */
