// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Curry                = require("bs-platform/lib/js/curry.js");
var Pervasives           = require("bs-platform/lib/js/pervasives.js");
var GraphqlTag           = require("graphql-tag");
var Apollo$ReactTemplate = require("./apollo.bs.js");

var mutation = GraphqlTag("\n  mutation RenameAlias($input: RenameAliasInput!) {\n    renameAlias(input: $input) {\n      error { code, message }\n      payload { actionTaken }\n    }\n  }\n");

var request = /* `Mutation */[
  1035765577,
  mutation
];

var Config = /* module */[/* request */request];

var Request = Apollo$ReactTemplate.Request(Config);

function run(name, newName) {
  var now = Pervasives.string_of_float(Date.now());
  var input = {
    clientMutationId: name + ("///" + (newName + ("///" + now))),
    name: name,
    newName: newName,
    disableAndAddIfUsed: true
  };
  return Curry._1(Request[/* send */3], /* Some */[{
                input: input
              }]);
}

exports.mutation = mutation;
exports.Config   = Config;
exports.Request  = Request;
exports.run      = run;
/* mutation Not a pure module */
