// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Curry                   = require("bs-platform/lib/js/curry.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

function map(f, param) {
  if (param) {
    return /* Some */[Curry._1(f, param[0])];
  } else {
    return /* None */0;
  }
}

function value(param) {
  if (param) {
    return param[0];
  } else {
    throw Caml_builtin_exceptions.not_found;
  }
}

function hasSome(param) {
  if (param) {
    return /* true */1;
  } else {
    return /* false */0;
  }
}

function hasNone(o) {
  return 1 - hasSome(o);
}

exports.map     = map;
exports.value   = value;
exports.hasSome = hasSome;
exports.hasNone = hasNone;
/* No side effect */
