// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Curry                = require("bs-platform/lib/js/curry.js");
var GraphqlTag           = require("graphql-tag");
var Url$ReactTemplate    = require("./url.bs.js");
var Apollo$ReactTemplate = require("./apollo.bs.js");

function str(prim) {
  return prim;
}

var query = GraphqlTag("\n  query GetAliasesByURL($url: AliasesURLInput) {\n    aliases(url: $url) {\n      error { code, message }\n      aliases { id, name, status }\n    }\n  }\n");

var Config = /* module */[];

var Query = Apollo$ReactTemplate.Query(Config);

function run(url) {
  var variables = /* Some */[{
      url: Url$ReactTemplate.toGql(url)
    }];
  return Curry._3(Query[/* send */3], /* Query */-250086680, query, variables);
}

exports.str    = str;
exports.query  = query;
exports.Config = Config;
exports.Query  = Query;
exports.run    = run;
/* query Not a pure module */
